rem Sandbox hardening script.
rem Hide VirtualBox registry values.
rem Original script: http://blog.prowling.nu/

reg copy HKLM\HARDWARE\ACPI\DSDT\VBOX__ HKLM\HARDWARE\ACPI\DSDT\BACKUP__ /s /f
reg delete HKLM\HARDWARE\ACPI\DSDT\VBOX__ /f
reg copy HKLM\HARDWARE\ACPI\RSDT\VBOX__  HKLM\HARDWARE\ACPI\RSDT\BACKUP__ /s /f
reg delete HKLM\HARDWARE\ACPI\RSDT\VBOX__ /f
reg copy HKLM\HARDWARE\ACPI\FADT\VBOX__ HKLM\HARDWARE\ACPI\FADT\BACKUP__ /s /f
reg delete HKLM\HARDWARE\ACPI\FADT\VBOX__ /f
reg copy HKEY_LOCAL_MACHINE\HARDWARE\ACPI\DSDT\BACKUP__\VBOXBIOS HKEY_LOCAL_MACHINE\HARDWARE\ACPI\DSDT\BACKUP__\BACKUPBIOS /s /f
reg delete HKEY_LOCAL_MACHINE\HARDWARE\ACPI\DSDT\BACKUP__\VBOXBIOS /f
reg copy HKEY_LOCAL_MACHINE\HARDWARE\ACPI\DSDT\BACKUP__\VBOXBIOS HKEY_LOCAL_MACHINE\HARDWARE\ACPI\DSDT\BACKUP__\BACKUPBIOS /s /f
reg delete HKEY_LOCAL_MACHINE\HARDWARE\ACPI\DSDT\BACKUP__\VBOXBIOS /f
reg copy HKEY_LOCAL_MACHINE\HARDWARE\ACPI\FADT\BACKUP__\VBOXFACP HKEY_LOCAL_MACHINE\HARDWARE\ACPI\FADT\BACKUP__\BACKUPFACP /s /f
reg delete HKEY_LOCAL_MACHINE\HARDWARE\ACPI\FADT\BACKUP__\VBOXFACP /f
reg copy HKEY_LOCAL_MACHINE\HARDWARE\ACPI\RSDT\BACKUP__\VBOXRSDT HKEY_LOCAL_MACHINE\HARDWARE\ACPI\RSDT\BACKUP__\BACKUPRSDT /s /f
reg delete HKEY_LOCAL_MACHINE\HARDWARE\ACPI\RSDT\BACKUP__\VBOXRSDT /f
reg copy HKEY_LOCAL_MACHINE\HARDWARE\ACPI\DSDT\BACKUP__\VBOXBIOS HKEY_LOCAL_MACHINE\HARDWARE\ACPI\DSDT\BACKUP__\BACKUPBIOS /s /f
reg delete HKEY_LOCAL_MACHINE\HARDWARE\ACPI\DSDT\BACKUP__\VBOXBIOS /f
reg copy HKEY_LOCAL_MACHINE\HARDWARE\ACPI\FADT\<VENDOR>\VBOXFACP HKEY_LOCAL_MACHINE\HARDWARE\ACPI\FADT\<VENDOR>\BACKUPFACP /s /f
reg delete HKEY_LOCAL_MACHINE\HARDWARE\ACPI\FADT\<VENDOR>\VBOXFACP /f
reg copy HKEY_LOCAL_MACHINE\HARDWARE\ACPI\RSDT\<VENDOR>\VBOXRSDT HKEY_LOCAL_MACHINE\HARDWARE\ACPI\RSDT\<VENDOR>\BACKUPRSDT /s /f
reg delete HKEY_LOCAL_MACHINE\HARDWARE\ACPI\RSDT\<VENDOR>\VBOXRSDT /f
reg add HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System /v SystemBiosVersion /t REG_MULTI_SZ /d "L71 Ver. 01.21" /f
reg add HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System /v VideoBiosVersion /t REG_MULTI_SZ /d "L71 Ver. 01.21" /f
